server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/messageservice?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 050708
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: none # 禁用Hibernate自动DDL

  mail:
    host: smtp.example.com
    port: 465
    username: your_email@example.com
    password: your_password
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

topbiz:
  feedback-url: http://localhost:8080/mock/feedback

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl